# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 0) do

  create_table "campaigns", :force => true do |t|
    t.column "name",               :string,  :limit => 64
    t.column "created_by_user_id", :integer, :limit => 4
  end

  create_table "character_skills", :force => true do |t|
    t.column "character_id",           :integer,               :null => false
    t.column "skill_id",               :integer,               :null => false
    t.column "trained",                :boolean
    t.column "misc_bonus",             :integer
    t.column "misc_bonus_description", :string,  :limit => 64
  end

  create_table "characters", :force => true do |t|
    t.column "user_id",              :integer
    t.column "name",                 :string,  :limit => 64
    t.column "sex",                  :string,  :limit => 0
    t.column "class_id",             :integer, :limit => 4
    t.column "race_id",              :integer, :limit => 4
    t.column "experience_points",    :integer
    t.column "level",                :integer, :limit => 4
    t.column "max_hit_points",       :integer, :limit => 4
    t.column "current_hit_points",   :integer, :limit => 4
    t.column "healing_surge",        :integer, :limit => 4
    t.column "surges_per_day",       :integer, :limit => 4
    t.column "surges_remaining",     :integer, :limit => 4
    t.column "action_points",        :integer, :limit => 4
    t.column "initiative",           :integer, :limit => 4
    t.column "armor_class",          :integer, :limit => 4
    t.column "misc_fortitude_bonus", :integer, :limit => 4
    t.column "misc_reflex_bonus",    :integer, :limit => 4
    t.column "misc_will_bonus",      :integer, :limit => 4
    t.column "height",               :string,  :limit => 8
    t.column "weight",               :integer, :limit => 4
    t.column "alignment",            :string,  :limit => 0
    t.column "strength",             :integer, :limit => 4
    t.column "constitution",         :integer, :limit => 4
    t.column "dexterity",            :integer, :limit => 4
    t.column "intellegence",         :integer, :limit => 4
    t.column "wisdom",               :integer, :limit => 4
    t.column "charisma",             :integer, :limit => 4
  end

  create_table "classes", :force => true do |t|
    t.column "name",                :string,  :limit => 32
    t.column "fortitude_def_bonus", :integer
    t.column "reflex_def_bonus",    :integer
    t.column "will_def_bonus",      :integer
  end

  create_table "feats", :force => true do |t|
    t.column "character_id",    :integer,                :null => false
    t.column "name",            :string,  :limit => 32
    t.column "description",     :string,  :limit => 128
    t.column "level_gained_at", :integer
  end

  create_table "powers", :force => true do |t|
    t.column "character_id",    :integer,                :null => false
    t.column "name",            :string,  :limit => 32
    t.column "description",     :string,  :limit => 128
    t.column "frequency",       :string,  :limit => 0
    t.column "level_gained_at", :integer
  end

  create_table "races", :force => true do |t|
    t.column "name",   :string,  :limit => 64
    t.column "speed",  :integer, :limit => 4
    t.column "size",   :string,  :limit => 0
    t.column "vision", :string,  :limit => 0
  end

  create_table "roles", :force => true do |t|
    t.column "name", :string, :limit => 64
  end

  create_table "skills", :force => true do |t|
    t.column "name",        :string, :limit => 32
    t.column "key_ability", :string, :limit => 32
  end

  create_table "users", :force => true do |t|
    t.column "email",    :string, :limit => 128
    t.column "password", :string, :limit => 64
    t.column "name",     :string, :limit => 64
  end

  create_table "users_campaigns", :force => true do |t|
    t.column "user_id",     :integer
    t.column "campaign_id", :integer
    t.column "role_id",     :integer
  end

  create_table "weapons", :force => true do |t|
    t.column "character_id", :integer,                :null => false
    t.column "name",         :string,  :limit => 32
    t.column "description",  :string,  :limit => 128
    t.column "key_ability",  :string,  :limit => 32
  end

end
